// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceOfMiniGames.WebApi.Data;

#nullable disable

namespace SpaceOfMiniGames.WebApi.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220805221046_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SpaceOfMiniGames.WebApi.Models.ModelsDbo.RoleDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Player"
                        });
                });

            modelBuilder.Entity("SpaceOfMiniGames.WebApi.Models.ModelsDbo.RoleRelationship", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SpaceOfMiniGames.WebApi.Models.ModelsDbo.UserDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "sirion",
                            PasswordHash = "81DC9BDB52D04DC20036DBD8313ED055",
                            RegistrationDate = new DateTime(2022, 8, 6, 1, 10, 45, 906, DateTimeKind.Local).AddTicks(6037)
                        });
                });

            modelBuilder.Entity("SpaceOfMiniGames.WebApi.Models.ModelsDbo.RoleRelationship", b =>
                {
                    b.HasOne("SpaceOfMiniGames.WebApi.Models.ModelsDbo.RoleDbo", "Role")
                        .WithMany("RoleRelationships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceOfMiniGames.WebApi.Models.ModelsDbo.UserDbo", "User")
                        .WithMany("RoleRelationships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceOfMiniGames.WebApi.Models.ModelsDbo.RoleDbo", b =>
                {
                    b.Navigation("RoleRelationships");
                });

            modelBuilder.Entity("SpaceOfMiniGames.WebApi.Models.ModelsDbo.UserDbo", b =>
                {
                    b.Navigation("RoleRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
